from criatura import Criatura

# Lista de criaturas con sus respectivos datos
criaturas = [
    Criatura("Ceto", derrotado_por=None, descripcion="Diosa primordial del mar, madre de monstruos marinos.", capturada=None),
    Criatura("Tifón", derrotado_por="Zeus", descripcion="Gigante con forma de serpiente que intentó destronar a Zeus.", capturada=None),
    Criatura("Equidna", derrotado_por="Argos Panoptes", descripcion="Ser mitad mujer, mitad serpiente.", capturada=None),
    Criatura("Dino", derrotado_por=None, descripcion="Monstruo marino hija de Forcis y Ceto.", capturada=None),
    Criatura("Pefredo", derrotado_por=None, descripcion="Una de las Grayas, hermanas que compartían un ojo y un diente.", capturada=None),
    Criatura("Enio", derrotado_por=None, descripcion="Otra de las Grayas, asociada con la guerra.", capturada=None),
    Criatura("Escila", derrotado_por=None, descripcion="Monstruo marino que devoraba marineros.", capturada=None),
    Criatura("Caribdis", derrotado_por=None, descripcion="Monstruo marino que tragaba enormes cantidades de agua.", capturada=None),
    Criatura("Euríale", derrotado_por=None, descripcion="Una de las Gorgonas.", capturada=None),
    Criatura("Esteno", derrotado_por=None, descripcion="Otra de las Gorgonas.", capturada=None),
    Criatura("Medusa", derrotado_por="Perseo", descripcion="La única mortal de las Gorgonas.", capturada=None),
    Criatura("Ladón", derrotado_por="Heracles", descripcion="Dragón guardián de las manzanas de oro.", capturada=None),
    Criatura("Águila del Cáucaso", derrotado_por=None, descripcion="Ave que devoraba el hígado de Prometeo.", capturada=None),
    Criatura("Quimera", derrotado_por="Belerofonte", descripcion="Monstruo con cabeza de león, cuerpo de cabra y cola de serpiente.", capturada=None),
    Criatura("Hidra de Lerna", derrotado_por="Heracles", descripcion="Monstruo acuático de múltiples cabezas.", capturada="Heracles"),
    Criatura("León de Nemea", derrotado_por="Heracles", descripcion="León invulnerable derrotado por Heracles.", capturada="Heracles"),
    Criatura("Esfinge", derrotado_por="Edipo", descripcion="Criatura con cuerpo de león y rostro de mujer.", capturada=None),
    Criatura("Cerda de Cromión", derrotado_por="Teseo", descripcion="Una cerda salvaje, hija de Tifón y Equidna.", capturada=None),
    Criatura("Ortro", derrotado_por="Heracles", descripcion="Un perro de dos cabezas, hermano de Cerbero.", capturada=None),
    Criatura("Toro de Creta", derrotado_por="Teseo", descripcion="Un toro blanco que Poseidón envió al rey Minos.", capturada=None),
    Criatura("Jabalí de Calidón", derrotado_por="Atalanta", descripcion="Un jabalí monstruoso enviado por Artemisa para castigar al rey Eneo.", capturada=None),
    Criatura("Carcinos", derrotado_por=None, descripcion="Un enorme cangrejo que atacó a Heracles.", capturada=None),
    Criatura("Gerión", derrotado_por="Heracles", descripcion="Un gigante de tres cuerpos, tres cabezas y seis brazos.", capturada=None),
    Criatura("Cloto", derrotado_por=None, descripcion="Una de las Moiras, las diosas del destino. Hilaba el hilo de la vida.", capturada=None),
    Criatura("Láquesis", derrotado_por=None, descripcion="Otra de las Moiras. Medía el hilo de la vida.", capturada=None),
    Criatura("Átropos", derrotado_por=None, descripcion="La tercera de las Moiras. Cortaba el hilo de la vida.", capturada=None),
    Criatura("Minotauro de Creta", derrotado_por="Teseo", descripcion="Criatura con cabeza de toro y cuerpo de hombre.", capturada=None),
    Criatura("Harpías", derrotado_por=None, descripcion="Criaturas mitad mujer, mitad pájaro, que robaban comida y castigaban a los malvados.", capturada=None),
    Criatura("Argos Panoptes", derrotado_por="Hermes", descripcion="Dios mensajero, protector de los viajeros y los ladrones.", capturada=None),
    Criatura("Aves del Estínfalo", derrotado_por=None, descripcion="Aves con picos de bronce y plumas metálicas que lanzaban como flechas.", capturada=None),
    Criatura("Talos", derrotado_por="Medea", descripcion="Un gigante de bronce, guardián de la isla de Creta.", capturada=None),
    Criatura("Sirenas", derrotado_por=None, descripcion="Criaturas mitad mujer, mitad ave, que atraían a los marineros con su canto.", capturada=None),
    Criatura("Pitón", derrotado_por="Apolo", descripcion="Una gran serpiente o dragón que vivía cerca del oráculo de Delfos.", capturada=None),
    Criatura("Cierva Cerinea", derrotado_por=None, descripcion="Una cierva con pezuñas de bronce y astas de oro, sagrada para Artemisa.", capturada=None),
    Criatura("Basilisco", derrotado_por=None, descripcion="Una criatura mítica, a menudo un reptil, con un aliento o mirada letal.", capturada=None),
    Criatura("Jabalí de Erimanto", derrotado_por=None, descripcion="Un jabalí salvaje que aterrorizaba una región del Peloponeso.", capturada=None),
    Criatura("Dragón de la Cólquida", derrotado_por=None, descripcion="Un dragón que custodiaba el Vellocino de Oro en la Cólquide.", capturada=None),
    Criatura("Cerbero", derrotado_por="Hermes", descripcion="El perro de tres cabezas que guardaba la entrada al inframundo.", capturada=None)
]
