from personaje import Personaje

personajes=[
    Personaje('Thor', 'Thor Odinson', False, 1962, 'Norse god of thunder, wielder of Mjolnir.'),
    Personaje('Hulk', 'Bruce Banner', False, 1962, 'Genius scientist exposed to gamma radiation, transforms into a giant green rage monster.'),
    Personaje('Black Widow', 'Natasha Romanoff', False, 1964, 'Highly skilled spy and assassin.'),
    Personaje('Dr Strang3', 'Stephen Strange', False, 1963, 'Former surgeon, now Sorcerer Supreme.'),
    Personaje('Black Panther', 'TChalla', False, 1966, 'King of Wakanda, protector of his nation.'),
    Personaje('Scarlet Witch', 'Wanda Maximoff', False, 1964, 'Powerful magic-user with reality-warping abilities.'),
    Personaje('Vision', 'Vision', False, 1968, 'Synthezoid created by Ultron, possesses incredible powers.'),
    Personaje('Ant-Man', 'Scott Lang', False, 1962, 'Thief who can shrink and grow, communicates with ants.'),
    Personaje('Wasp', 'Hope van Dyne', False, 1963, 'Co-hero with Ant-Man, can shrink and fly.'),
    Personaje('Hawkeye', 'Clint Barton', False, 1964, 'Master archer and expert marksman.'),
    Personaje('Falcon', 'Sam Wilson', False, 1969, 'Winged superhero, close ally of Captain America.'),
    Personaje('Winter Soldier', 'Bucky Barnes', False, 1941, 'Captain America\'s best friend, brainwashed assassin.'),
    Personaje('War Machine', 'James Rhodes', False, 1979, 'Tony Stark\'s best friend, wears a heavily armed Iron Man suit.'),
    Personaje('Daredevil', 'Matt Murdock', False, 1964, 'Blind lawyer with enhanced senses, fights crime in Hell\'s Kitchen.'),
    Personaje('Jessica Jones', 'Jessica Jones', False, 2001, 'Private investigator with super strength and flight.'),
    Personaje('Luke Cage', 'Luke Cage', False, 1972, 'Man with unbreakable skin and super strength.'),
    Personaje('Iron Fist', 'Danny Rand', False, 1974, 'Martial artist with a glowing chi-powered fist.'),
    Personaje('Punisher', 'Frank Castle', False, 1974, 'Vigilante who uses lethal force against criminals.'),
    Personaje('Blade', 'Eric Brooks', False, 1973, 'Half-human, half-vampire hunter.'),
    Personaje('Ghost Rider', 'Johnny Blaze', False, 1972, 'Stunt motorcyclist possessed by a demon.'),
    Personaje('Deadpool', 'Wade Wilson', False, 1991, 'Mercenary with a healing factor and a sarcastic wit.'),
    Personaje('Wolverine', 'James Howlett', False, 1974, 'Mutant with adamantium claws and a healing factor.'),
    Personaje('Storm', 'Ororo Munroe', False, 1975, 'Mutant with control over weather.'),
    Personaje('Cyclops', 'Scott Summers', False, 1963, 'Leader of the X-Men, projects optic blasts.'),
    Personaje('Jean Grey', 'Jean Grey', False, 1963, 'Telepath and telekinetic, host of the Phoenix Force.'),
    Personaje('Professor X', 'Charles Xavier', False, 1963, 'Powerful telepath, founder of the X-Men.'),
    Personaje('Magneto', 'Max Eisenhardt', True, 1963, 'Mutant with control over magnetism, often an adversary of the X-Men.'),
    Personaje('Mystique', 'Raven Darkhölme', True, 1978, 'Shape-shifting mutant.'),
    Personaje('Nightcrawler', 'Kurt Wagner', False, 1975, 'Mutant with teleportation abilities.'),
    Personaje('Beast', 'Hank McCoy', False, 1963, 'Brilliant scientist and mutant with enhanced agility.'),
    Personaje('Rogue', 'Anna Marie', False, 1981, 'Mutant who can absorb powers and memories through touch.'),
    Personaje('Gambit', 'Remy LeBeau', False, 1990, 'Mutant with the ability to charge objects with kinetic energy.'),
    Personaje('Colossus', 'Piotr Rasputin', False, 1975, 'Mutant who can transform his skin into organic steel.'),
    Personaje('Psylocke', 'Betsy Braddock', False, 1976, 'Telepath and telekinetic ninja.'),
    Personaje('Iceman', 'Robert Drake', False, 1963, 'Mutant with cryokinetic abilities.'),
    Personaje('Angel', 'Warren Worthington III', False, 1963, 'Mutant with feathered wings.'),
    Personaje('Emma Frost', 'Emma Frost', True, 1980, 'Powerful telepath, sometimes an ally, sometimes an adversary.'),
    Personaje('Sabretooth', 'Victor Creed', True, 1977, 'Feral mutant with a healing factor, Wolverine\'s nemesis.'),
    Personaje('Dr Doom', 'Victor Von Doom', True, 1962, 'Dictator of Latveria, brilliant scientist and sorcerer.'),
    Personaje('Galactus', 'Galan', True, 1966, 'Cosmic entity who consumes planets.'),
    Personaje('Silver Surfer', 'Norrin Radd', False, 1966, 'Herald of Galactus, possesses cosmic power.'),
    Personaje('Green Goblin', 'Norman Osborn', True, 1964, 'Insane industrialist, Spider-Man\'s arch-nemesis.'),
    Personaje('Dr Octopus', 'Otto Octavius', True, 1963, 'Brilliant but mad scientist with four mechanical tentacles.'),
    Personaje('Venom', 'Eddie Brock', True, 1988, 'Alien symbiote bonded with a human, often an anti-hero.'),
    Personaje('Carnage', 'Cletus Kasady', True, 1992, 'Psychopathic serial killer bonded with a symbiote, far more dangerous than Venom.'),
    Personaje('Kingpin', 'Wilson Fisk', True, 1967, 'Powerful crime lord of New York City.'),
    Personaje('Bullseye', 'Lester', True, 1976, 'Psychotic assassin with perfect aim.'),
    Personaje('Elektra', 'Elektra Natchios', False, 1981, 'Ninja assassin, love interest of Daredevil.'),
    Personaje('Red Skull', 'Johann Schmidt', True, 1947, 'Nazi agent, Captain America\'s arch-nemesis.'),
    Personaje('Ultron', 'Ultron', True, 1968, 'Artificially intelligent robot bent on human extinction.'),
    Personaje('Kang the Conqueror', 'Nathaniel Richards', True, 1964, 'time-traveling despot.'),
    Personaje('Annihilus', 'Annihilus', True, 1968, 'Insectoid ruler of the Negative Zone.'),
    Personaje('Dormammu', 'Dormammu', True, 1964, 'Powerful mystic entity from the Dark Dimension.'),
    Personaje('Mysterio', 'Quentin Beck', True, 1964, 'Special effects wizard and illusionist.'),
    Personaje('Vulture', 'Adrian Toomes', True, 1964, 'Elderly engineer with a winged suit.'),
    Personaje('Sandman', 'Flint Marko', True, 1963, 'Criminal with the ability to turn into sand.'),
    Personaje('Electro', 'Max Dillon', True, 1964, 'Electrician who gained electrical powers.'),
    Personaje('Rhino', 'Aleksei Sytsevich', True, 1966, 'Russian thug with an indestructible suit.'),
    Personaje('Kraven the Hunter', 'Sergei Kravinoff', True, 1964, 'Big-game hunter obsessed with hunting Spider-Man.'),
    Personaje('Scorpion', 'Mac Gargan', True, 1964, 'Private investigator turned supervillain with a scorpion suit.'),
    Personaje('Shocker', 'Herman Schultz', True, 1967, 'Vibration-emitting supervillain.'),
    Personaje('Hobgoblin', 'Roderick Kingsley', True, 1983, 'Costumed criminal who uses similar gear to the Green Goblin.'),
    Personaje('Morbius', 'Michael Morbius', False, 1971, 'Biochemist who became a living vampire.'),
    Personaje('Werewolf by Night', 'Jack Russell', False, 1972, 'Man cursed to transform into a werewolf.'),
    Personaje('Man-Thing', 'Ted Sallis', False, 1971, 'Swamp monster in the Florida Everglades.'),
    Personaje('Howard the Duck', 'Howard the Duck', False, 1973, 'Anthropomorphic duck from another dimension.'),
    Personaje('Squirrel Girl', 'Doreen Green', False, 1992, 'Superhero with squirrel-like abilities and an optimistic attitude.'),
    Personaje('She-Hulk', 'Jennifer Walters', False, 1980, 'Lawyer who gained Hulk-like powers from a blood transfusion.'),
    Personaje('Captain Marvel', 'Carol Danvers', False, 1968, 'Air Force pilot with cosmic powers.'),
    Personaje('Ms. Marvel', 'Kamala Khan', False, 2013, 'Pakistani-American teenager with shapeshifting abilities.'),
    Personaje('Nova', 'Richard Rider', False, 1976, 'Teenager imbued with the power of the Nova Force.'),
    Personaje('Star-Lord', 'Peter Quill', False, 1976, 'Leader of the Guardians of the Galaxy, half-human, half-Spartoi.'),
    Personaje('Gamora', 'Gamora', False, 1975, 'Adopted daughter of Thanos, deadliest woman in the galaxy.'),
    Personaje('Drax the Destroyer', 'Arthur Douglas', False, 1973, 'Man seeking revenge on Thanos for the death of his family.'),
    Personaje('Rocket Raccoon', 'Rocket Raccoon', False, 1976, 'Genetically engineered raccoon, expert marksman and tactician.'),
    Personaje('Groot', 'Groot', False, 1960, 'Sentient tree-like being, member of the Guardians of the Galaxy.'),
    Personaje('Ronan the Accuser', 'Ronan', True, 1967, 'Kree fundamentalist, often an antagonist.'),
    Personaje('Nebula', 'Nebula', True, 1985, 'Adopted daughter of Thanos, cybernetically enhanced assassin.'),
    Personaje('Mantis', 'Mantis', False, 1973, 'Empath with martial arts skills.'),
    Personaje('Adam Warlock', 'Adam Warlock', False, 1967, 'Artificially created being with cosmic powers.'),
    Personaje('Hela', 'Hela', True, 1964, 'Asgardian goddess of death, Thor\'s elder sister.'),
    Personaje('Surtur', 'Surtur', True, 1963, 'Fire demon, prophesied to destroy Asgard.'),
    Personaje('Ego the Living Planet', 'Ego', True, 1966, 'Ancient cosmic entity, a sentient planet.'),
    Personaje('Yondu Udonta', 'Yondu Udonta', False, 1964, 'Leader of the Ravagers, skilled with a Yaka Arrow.'),
    Personaje('Nick Fury', 'Nicholas Fury', False, 1963, 'Director of S.H.I.E.L.D.'),
    Personaje('Maria Hill', 'Maria Hill', False, 2005, 'High-ranking agent of S.H.I.E.L.D.'),
    Personaje('Phil Coulson', 'Phil Coulson', False, 2008, 'S.H.I.E.L.D. agent, often seen in the MCU.'),
    Personaje('Happy Hogan', 'Harold Hogan', False, 1963, 'Tony Stark\'s bodyguard and chauffeur.'),
    Personaje('Pepper Potts', 'Virginia Potts', False, 1963, 'Tony Stark\'s assistant and CEO of Stark Industries.'),
    Personaje('Valkyrie', 'Brunnhilde', False, 1970, 'Asgardian warrior, leader of New Asgard.'),
    Personaje('Korg', 'Korg', False, 2006, 'Kronan warrior, ally of Thor.'),
    Personaje('Miek', 'Miek', False, 2006, 'Insectoid warrior, ally of Thor.'),
    Personaje('Shang-Chi', 'Shang-Chi', False, 1973, 'Master of martial arts, wielder of the Ten Rings.'),
    Personaje('Wenwu', 'Wenwu', True, 1973, 'Leader of the Ten Rings, father of Shang-Chi.'),
    Personaje('America Chavez', 'America Chavez', False, 2011, 'Young hero with the ability to open star-shaped portals.'),
    Personaje('Kate Bishop', 'Kate Bishop', False, 2005, 'Skilled archer, protegé of Hawkeye.'),
    Personaje('Moon Knight', 'Marc Spector', False, 1975, 'Former mercenary, avatar of the Egyptian moon god Khonshu.'),
    Personaje('Ms. Marvel (Captain Marvel)', 'Kamala Khan', False, 2013, 'Teenage superhero with polymorphic powers.'),
    Personaje('Mister Fantastic', 'Reed Richards', False, 1961, 'Leader of the Fantastic Four, stretches his body.'),
    Personaje('Invisible Woman', 'Susan Storm Richards', False, 1961, 'Member of the Fantastic Four, turns invisible and creates force fields.'),
    Personaje('Human Torch', 'Johnny Storm', False, 1961, 'Member of the Fantastic Four, can engulf himself in flames and fly.'),
    Personaje('The Thing', 'Ben Grimm', False, 1961, 'Member of the Fantastic Four, transformed into a rock-like creature.'),
    Personaje('Silvermane', 'Silvio Manfredi', True, 1967, 'Elderly crime boss who uses cybernetic enhancements.'),
    Personaje('Baron Zemo', 'Helmut Zemo', True, 1964, 'Master strategist and terrorist, hates super-powered individuals.'),
    Personaje('Taskmaster', 'Antonia Dreykov', True, 1980, 'Photographic reflexes, can mimic any fighting style.'),
    Personaje('Baron Mordo', 'Karl Mordo', True, 1964, 'Former master of the mystic arts, now an antagonist to Dr Strange.'),
    Personaje('Nightmare', 'Nightmare', True, 1947, 'Ruler of the Dream Dimension, feeds on fear.'),
    Personaje('The Leader', 'Samuel Sterns', True, 1964, 'Exposed to gamma radiation, gained super-intelligence and a massive head.'),
    Personaje("Ant Man", "Scott Lang",True, 1979, "Un ex-ladrón que se convierte en superhéroe al utilizar un traje que le permite reducir su tamaño."),
]